# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPLNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
