# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPLNews', '0003_player_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('gp', models.IntegerField()),
                ('won', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('gs', models.IntegerField()),
                ('ga', models.IntegerField()),
                ('gd', models.IntegerField()),
                ('point', models.IntegerField()),
                ('recent_form', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
