# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPLNews', '0004_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='logo_url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
