# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPLNews', '0005_standing_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
