# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPLNews', '0008_auto_20170817_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('logo_url', models.CharField(max_length=255)),
                ('assist', models.IntegerField()),
                ('nationality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('logo_url', models.CharField(max_length=255)),
                ('card', models.IntegerField()),
                ('nationality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('logo_url', models.CharField(max_length=255)),
                ('goal', models.IntegerField()),
                ('nationality', models.CharField(max_length=30)),
            ],
        ),
    ]
