# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPLNews', '0009_assist_card_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assist',
            name='img_url',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='img_url',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='score',
            name='img_url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
